export const cardData = [
  {
    id: 1,
    name: "Nike Air Force 1 High SE",
    category: "Women's Shoes",
    price: 11750,
    imgUrl: "/shoe1.webp",
  },
  {
    id: 2,
    name: "Nike Air Force 1 '07 LV8",
    category: "Men's Shoes",
    price: 9695,
    imgUrl: "/shoe2.webp",
  },
  {
    id: 3,
    name: "Nike Force 1 Low SE",
    category: "Younger Kid's Shoes",
    price: 5995,
    imgUrl: "/shoe3.webp",
  },
  {
    id: 4,
    name: "Nike Air Force 1 React",
    category: "Men's Shoes",
    price: 11995,
    imgUrl: "/shoe4.webp",
  },
  {
    id: 5,
    name: "Nike Air Force 1 Mid SE",
    category: "Men's Shoes",
    price: 12995,
    imgUrl: "/shoe5.webp",
  },
  {
    id: 6,
    name: "Nike Force 1 Low SE",
    category: "Baby Toddler Shoes",
    price: 4495,
    imgUrl: "/shoe6.webp",
  },
  {
    id: 7,
    name: "Nike Air Force 1 '07 SE",
    category: "Women's Shoes",
    price: 9695,
    imgUrl: "/shoe7.webp",
  },
  {
    id: 8,
    name: "Nike Air Force 1 Mid '07 LV8",
    category: "Men's Shoes",
    price: 10795,
    imgUrl: "/shoe8.webp",
  },
];
